name: "Hit a webhook"

on:
  workflow_dispatch: 
  push:
    tags:
      - '**'
 
jobs:
  run_updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://example.com/api/v2/endpoint"
        | exit 1

  notify_backend:
    if: ${{ always() }}
    needs: [run_updater]
    runs-on: ubuntu-latest
    steps: 
    - name: Notify the Backend about the execution Status
      # run: echo "Hello"
      run: echo "${{ needs.run_updater.conclusion }}"

    - name: Notify for Success
      env:
          JOB_CONTEXT: ${{ toJson(job) }}
      if: ${{ needs.run_updater.result == 'success' }}
      run: echo "post success $JOB_CONTEXT"

    - name: Notify for Error
      env:
          JOB_CONTEXT: ${{ toJson(needs) }}
      if: ${{ needs.run_updater.result == 'failure' }}
      run: echo "post error $JOB_CONTEXT"

    - name: Notify for Job Cancellation
      env:
          JOB_CONTEXT: ${{ toJson(github) }}
      if: ${{ needs.run_updater.result == 'cancelled' }}
      run: echo "post cancellation $JOB_CONTEXT"
