name: "Hit a webhook"

on:
  workflow_dispatch: 
  push:
    tags:
      - '**'
 
jobs:
  run_updater:
    runs-on: ubuntu-latest
    steps:
    - name: fail intentionally
      run: exit 1        

  notify_backend:
    if: ${{ always() }}
    needs: [run_updater]
    runs-on: ubuntu-latest
    steps: 
    - name: Notify the Backend about the execution Status
      # run: echo "Hello"
      run: echo "${{ needs.run_updater.conclusion }}"

    - name: Notify for Success
      env:
          JOB_CONTEXT: ${{ toJson(job) }}
      if: ${{ needs.run_updater.result == 'success' }}
      run: |
          curl -i -H "Accept:application/json" -H "Content-Type:application/json" \
          -H "Authorization: Bearer ACCESS-TOKEN" -XPOST "https://gorest.co.in/public/v2/users" \
          -d '{"name":"Tenali Ramakrishna", "gender":"male", "email":"tenali.ramakrishna@15ce.com", "status":"active"}'

    - name: Notify for Error
      env:
          JOB_CONTEXT: ${{ toJson(needs) }}
      if: ${{ needs.run_updater.result == 'failure' }}
      run: |
          curl -i -H "Accept:application/json" -H "Content-Type:application/json" \
          -H "Authorization: Bearer ACCESS-TOKEN" -XPOST "https://gorest.co.in/public/v2/users" \
          -d '{"name":"Tenali Ramakrishna", "gender":"male", "email":"tenali.ramakrishna@15ce.com", "status":"active"}'

    - name: Notify for Job Cancellation
      env:
          JOB_CONTEXT: ${{ toJson(github) }}
      if: ${{ needs.run_updater.result == 'cancelled' }}
      run: |
          curl -i -H "Accept:application/json" -H "Content-Type:application/json" \
          -H "Authorization: Bearer ACCESS-TOKEN" -XPOST "https://gorest.co.in/public/v2/users" \
          -d '{"name":"Tenali Ramakrishna", "gender":"male", "email":"tenali.ramakrishna@15ce.com", "status":"active"}'
