name: "Hit a webhook"

on:
  workflow_dispatch: 
  push:
    tags:
      - '**'
 
jobs:
  run_updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://example.com/api/v2/endpoint"
        | exit 1

  notify_backend:
    if: ${{ always() }}
    needs: [run_updater]
    runs-on: ubuntu-latest
    steps: 
    - name: Notify the Backend about the execution Status
      # run: echo "Hello"
      run: echo "${{ needs.run_updater.conclusion }}"

    - name: Notify for Success
      if: ${{ needs.run_updater.conclusion == 'success' }}
      run: echo "post success"

    - name: Notify for Error
      if: ${{ needs.run_updater.conclusion == 'failure' }}
      run: echo "post error"

    - name: Notify for Job Cancellation
      if: ${{ needs.run_updater.conclusion == 'cancelled' }}
      run: echo "post cancellation"
